package com.applovin.impl;

/* JADX INFO: loaded from: classes3.dex */
public abstract class ue extends com.applovin.impl.sj {
    public static final com.applovin.impl.sj A7;
    public static final com.applovin.impl.sj B7;
    public static final com.applovin.impl.sj C7;
    public static final com.applovin.impl.sj D6 = com.applovin.impl.sj.a("afi", "");
    public static final com.applovin.impl.sj D7;
    public static final com.applovin.impl.sj E6;
    public static final com.applovin.impl.sj E7;
    public static final com.applovin.impl.sj F6;
    public static final com.applovin.impl.sj F7;
    public static final com.applovin.impl.sj G6;
    public static final com.applovin.impl.sj G7;
    public static final com.applovin.impl.sj H6;
    public static final com.applovin.impl.sj H7;
    public static final com.applovin.impl.sj I6;
    public static final com.applovin.impl.sj I7;
    public static final com.applovin.impl.sj J6;
    public static final com.applovin.impl.sj J7;
    public static final com.applovin.impl.sj K6;
    public static final com.applovin.impl.sj K7;
    public static final com.applovin.impl.sj L6;
    public static final com.applovin.impl.sj L7;
    public static final com.applovin.impl.sj M6;
    public static final com.applovin.impl.sj M7;
    public static final com.applovin.impl.sj N6;
    public static final com.applovin.impl.sj N7;
    public static final com.applovin.impl.sj O6;
    public static final com.applovin.impl.sj O7;
    public static final com.applovin.impl.sj P6;
    public static final com.applovin.impl.sj Q6;
    public static final com.applovin.impl.sj R6;
    public static final com.applovin.impl.sj S6;
    public static final com.applovin.impl.sj T6;
    public static final com.applovin.impl.sj U6;
    public static final com.applovin.impl.sj V6;
    public static final com.applovin.impl.sj W6;
    public static final com.applovin.impl.sj X6;
    public static final com.applovin.impl.sj Y6;
    public static final com.applovin.impl.sj Z6;
    public static final com.applovin.impl.sj a7;
    public static final com.applovin.impl.sj b7;
    public static final com.applovin.impl.sj c7;
    public static final com.applovin.impl.sj d7;
    public static final com.applovin.impl.sj e7;
    public static final com.applovin.impl.sj f7;
    public static final com.applovin.impl.sj g7;
    public static final com.applovin.impl.sj h7;
    public static final com.applovin.impl.sj i7;
    public static final com.applovin.impl.sj j7;
    public static final com.applovin.impl.sj k7;
    public static final com.applovin.impl.sj l7;
    public static final com.applovin.impl.sj m7;
    public static final com.applovin.impl.sj n7;
    public static final com.applovin.impl.sj o7;
    public static final com.applovin.impl.sj p7;
    public static final com.applovin.impl.sj q7;
    public static final com.applovin.impl.sj r7;
    public static final com.applovin.impl.sj s7;
    public static final com.applovin.impl.sj t7;
    public static final com.applovin.impl.sj u7;
    public static final com.applovin.impl.sj v7;
    public static final com.applovin.impl.sj w7;
    public static final com.applovin.impl.sj x7;
    public static final com.applovin.impl.sj y7;
    public static final com.applovin.impl.sj z7;

    static {
        java.util.concurrent.TimeUnit timeUnit = java.util.concurrent.TimeUnit.SECONDS;
        E6 = com.applovin.impl.sj.a("afi_ms", java.lang.Long.valueOf(timeUnit.toMillis(5L)));
        F6 = com.applovin.impl.sj.a("mediation_endpoint", "https://ms.applovin.com/");
        G6 = com.applovin.impl.sj.a("mediation_backup_endpoint", "https://ms.applvn.com/");
        H6 = com.applovin.impl.sj.a("fetch_next_ad_retry_delay_ms", java.lang.Long.valueOf(timeUnit.toMillis(2L)));
        I6 = com.applovin.impl.sj.a("fetch_next_ad_timeout_ms", java.lang.Long.valueOf(timeUnit.toMillis(30L)));
        J6 = com.applovin.impl.sj.a("fetch_mediation_debugger_info_timeout_ms", java.lang.Long.valueOf(timeUnit.toMillis(7L)));
        java.lang.Boolean bool = java.lang.Boolean.TRUE;
        K6 = com.applovin.impl.sj.a("auto_init_mediation_debugger", bool);
        L6 = com.applovin.impl.sj.a("postback_macros", "{\"{MCODE}\":\"mcode\",\"{BCODE}\":\"bcode\",\"{ICODE}\":\"icode\",\"{SCODE}\":\"scode\"}");
        M6 = com.applovin.impl.sj.a("max_signal_provider_latency_ms", java.lang.Long.valueOf(timeUnit.toMillis(30L)));
        N6 = com.applovin.impl.sj.a("default_adapter_timeout_ms", java.lang.Long.valueOf(timeUnit.toMillis(10L)));
        O6 = com.applovin.impl.sj.a("ad_refresh_ms", java.lang.Long.valueOf(timeUnit.toMillis(30L)));
        P6 = com.applovin.impl.sj.a("ad_load_failure_refresh_ms", java.lang.Long.valueOf(timeUnit.toMillis(30L)));
        Q6 = com.applovin.impl.sj.a("ad_load_failure_refresh_ignore_error_codes", "204");
        R6 = com.applovin.impl.sj.a("refresh_ad_on_app_resume_elapsed_threshold_ms", 0L);
        S6 = com.applovin.impl.sj.a("refresh_ad_view_timer_responds_to_background", bool);
        T6 = com.applovin.impl.sj.a("refresh_ad_view_timer_responds_to_store_kit", bool);
        java.lang.Boolean bool2 = java.lang.Boolean.FALSE;
        U6 = com.applovin.impl.sj.a("refresh_ad_view_timer_responds_to_window_visibility_changed", bool2);
        V6 = com.applovin.impl.sj.a("avrsponse", bool2);
        W6 = com.applovin.impl.sj.a("allow_pause_auto_refresh_immediately", bool2);
        X6 = com.applovin.impl.sj.a("ad_view_race_condition_fix_enabled", bool2);
        Y6 = com.applovin.impl.sj.a("fullscreen_display_delay_ms", 0L);
        Z6 = com.applovin.impl.sj.a("susaode", bool2);
        a7 = com.applovin.impl.sj.a("ahdm", 500L);
        b7 = com.applovin.impl.sj.a("ad_view_refresh_precache_request_viewability_undesired_flags", 246L);
        c7 = com.applovin.impl.sj.a("ad_view_refresh_precache_request_enabled", bool);
        d7 = com.applovin.impl.sj.a("famttl_ms", 0L);
        e7 = com.applovin.impl.sj.a("signal_expiration_ms", -1L);
        f7 = com.applovin.impl.sj.a("signal_cache_level", java.lang.Integer.valueOf(com.applovin.impl.xj.b.AD_FORMAT.ordinal()));
        java.util.concurrent.TimeUnit timeUnit2 = java.util.concurrent.TimeUnit.HOURS;
        g7 = com.applovin.impl.sj.a("ad_expiration_ms", java.lang.Long.valueOf(timeUnit2.toMillis(4L)));
        h7 = com.applovin.impl.sj.a("native_ad_expiration_ms", java.lang.Long.valueOf(timeUnit2.toMillis(4L)));
        i7 = com.applovin.impl.sj.a("rena", bool);
        j7 = com.applovin.impl.sj.a("fullscreen_ad_displayed_timeout_ms", -1L);
        k7 = com.applovin.impl.sj.a("freast_ms", -1L);
        l7 = com.applovin.impl.sj.a("ad_hidden_timeout_ms", -1L);
        m7 = com.applovin.impl.sj.a("schedule_ad_hidden_on_ad_dismiss", bool2);
        n7 = com.applovin.impl.sj.a("schedule_ad_hidden_on_single_task_app_relaunch", bool2);
        o7 = com.applovin.impl.sj.a("ad_hidden_on_ad_dismiss_callback_delay_ms", java.lang.Long.valueOf(timeUnit.toMillis(1L)));
        p7 = com.applovin.impl.sj.a("proe", bool2);
        q7 = com.applovin.impl.sj.a("mute_state", 2);
        r7 = com.applovin.impl.sj.a("saf", "");
        s7 = com.applovin.impl.sj.a("saui", "");
        t7 = com.applovin.impl.sj.a("mra", -1);
        u7 = com.applovin.impl.sj.a("mra_af", "INTER,REWARDED,REWARDED_INTER,BANNER,LEADER,MREC");
        v7 = com.applovin.impl.sj.a("svadfr", bool2);
        w7 = com.applovin.impl.sj.a("fadiafase", bool);
        x7 = com.applovin.impl.sj.a("fadwvcv", bool);
        y7 = com.applovin.impl.sj.a("bfarud", bool2);
        z7 = com.applovin.impl.sj.a("inacc", java.lang.Boolean.valueOf(com.applovin.impl.yp.b(java.util.Arrays.asList("com.textmeinc.textme", "com.textmeinc.freetone", "com.textmeinc.textme3", "com.jaumo", "com.jaumo.casual", "com.pinkapp", "com.jaumo.mature", "com.jaumo.prime", "com.jaumo.gay", "com.jaumo.lesbian"))));
        A7 = com.applovin.impl.sj.a("pbataipaf", "");
        B7 = com.applovin.impl.sj.a("bwt_ms", java.lang.Long.valueOf(timeUnit.toMillis(30L)));
        C7 = com.applovin.impl.sj.a("twt_ms", java.lang.Long.valueOf(timeUnit.toMillis(30L)));
        D7 = com.applovin.impl.sj.a("adiets_sec", java.lang.Long.valueOf(java.util.concurrent.TimeUnit.MINUTES.toSeconds(1L)));
        E7 = com.applovin.impl.sj.a("faomq", bool2);
        F7 = com.applovin.impl.sj.a("siflcfbt", bool2);
        G7 = com.applovin.impl.sj.a("rahcnct_sec", -1);
        H7 = com.applovin.impl.sj.a("uabta", bool2);
        I7 = com.applovin.impl.sj.a("use_initialization_spec_during_init", bool2);
        J7 = com.applovin.impl.sj.a("use_promises_during_init", bool2);
        K7 = com.applovin.impl.sj.a("report_cimp_after_ierr", bool2);
        L7 = com.applovin.impl.sj.a("fail_collection_for_empty_signal", bool2);
        M7 = com.applovin.impl.sj.a("sdaomq", bool2);
        N7 = com.applovin.impl.sj.a("fetch_mediated_ad_gzip", bool);
        O7 = com.applovin.impl.sj.a("max_postback_gzip", bool);
    }
}
