package com.bytedance.sdk.openadsdk.Ta;

/* JADX INFO: loaded from: classes4.dex */
public class Ta extends com.bytedance.sdk.openadsdk.core.zx.iR {
    public Ta(android.content.Context context) {
        this(context, null);
    }

    public Ta(android.content.Context context, android.util.AttributeSet attributeSet) {
        this(context, attributeSet, 0);
    }

    public Ta(android.content.Context context, android.util.AttributeSet attributeSet, int i) {
        super(context, attributeSet, i);
        bg(context);
    }

    private void bg(android.content.Context context) {
        setId(520093726);
        setBackgroundColor(-1);
        com.bytedance.sdk.openadsdk.core.zx.iR iRVar = new com.bytedance.sdk.openadsdk.core.zx.iR(context);
        iRVar.setId(com.bytedance.sdk.openadsdk.utils.Ta.uny);
        iRVar.setLayoutParams(new android.widget.RelativeLayout.LayoutParams(-1, -1));
        iRVar.setBackgroundColor(0);
        iRVar.setGravity(17);
        addView(iRVar);
        com.bytedance.sdk.openadsdk.core.zx.eqN eqn = new com.bytedance.sdk.openadsdk.core.zx.eqN(context);
        eqn.setId(com.bytedance.sdk.openadsdk.utils.Ta.JxS);
        eqn.setLayoutParams(new android.widget.RelativeLayout.LayoutParams(-1, -1));
        iRVar.addView(eqn);
        com.bytedance.sdk.openadsdk.core.zx.ldr ldrVar = new com.bytedance.sdk.openadsdk.core.zx.ldr(context);
        ldrVar.setId(com.bytedance.sdk.openadsdk.utils.Ta.KRc);
        int iBX = com.bytedance.sdk.openadsdk.utils.ZQc.bX(context, 60.0f);
        android.widget.RelativeLayout.LayoutParams layoutParams = new android.widget.RelativeLayout.LayoutParams(iBX, iBX);
        layoutParams.addRule(13);
        ldrVar.setLayoutParams(layoutParams);
        ldrVar.setIndeterminateDrawable(com.bytedance.sdk.openadsdk.utils.Kg.bg(context, "tt_video_loading_progress_bar"));
        iRVar.addView(ldrVar);
        com.bytedance.sdk.openadsdk.core.zx.zx zxVar = new com.bytedance.sdk.openadsdk.core.zx.zx(context);
        zxVar.setId(com.bytedance.sdk.openadsdk.utils.Ta.JlG);
        android.widget.RelativeLayout.LayoutParams layoutParams2 = new android.widget.RelativeLayout.LayoutParams(-2, -2);
        layoutParams2.addRule(13);
        zxVar.setLayoutParams(layoutParams2);
        zxVar.setGravity(1);
        zxVar.setOrientation(1);
        zxVar.setVisibility(8);
        iRVar.addView(zxVar);
        com.bytedance.sdk.openadsdk.core.zx.eqN eqn2 = new com.bytedance.sdk.openadsdk.core.zx.eqN(context);
        eqn2.setId(com.bytedance.sdk.openadsdk.utils.Ta.mZk);
        eqn2.setLayoutParams(new android.widget.LinearLayout.LayoutParams(-2, -2));
        eqn2.setImageDrawable(com.bytedance.sdk.openadsdk.utils.Kg.bg(context, "tt_refreshing_video_textpage"));
        eqn2.setScaleType(android.widget.ImageView.ScaleType.CENTER);
        zxVar.addView(eqn2);
        com.bytedance.sdk.openadsdk.core.zx.Kg kg = new com.bytedance.sdk.openadsdk.core.zx.Kg(context);
        kg.setId(com.bytedance.sdk.openadsdk.utils.Ta.mLT);
        kg.setLayoutParams(new android.widget.LinearLayout.LayoutParams(-2, -2));
        kg.setText(com.bytedance.sdk.component.utils.Fy.bg(context, "tt_video_retry_des_txt"));
        kg.setTextColor(android.graphics.Color.parseColor("#999999"));
        zxVar.addView(kg);
        com.bytedance.sdk.openadsdk.core.zx.eqN eqn3 = new com.bytedance.sdk.openadsdk.core.zx.eqN(context);
        eqn3.setId(com.bytedance.sdk.openadsdk.utils.Ta.yda);
        android.widget.RelativeLayout.LayoutParams layoutParams3 = new android.widget.RelativeLayout.LayoutParams(-2, -2);
        layoutParams3.addRule(13);
        eqn3.setLayoutParams(layoutParams3);
        eqn3.setScaleType(android.widget.ImageView.ScaleType.CENTER);
        eqn3.setImageDrawable(com.bytedance.sdk.openadsdk.utils.Kg.bg(context, "tt_play_movebar_textpage"));
        eqn3.setVisibility(8);
        addView(eqn3);
        com.bytedance.sdk.openadsdk.core.zx.eqN eqn4 = new com.bytedance.sdk.openadsdk.core.zx.eqN(context);
        eqn4.setId(com.bytedance.sdk.openadsdk.utils.Ta.uV);
        int iBX2 = com.bytedance.sdk.openadsdk.utils.ZQc.bX(context, 30.0f);
        android.widget.RelativeLayout.LayoutParams layoutParams4 = new android.widget.RelativeLayout.LayoutParams(iBX2, iBX2);
        layoutParams4.addRule(21);
        layoutParams4.addRule(11);
        int iBX3 = com.bytedance.sdk.openadsdk.utils.ZQc.bX(context, 7.0f);
        layoutParams4.setMarginEnd(iBX3);
        layoutParams4.rightMargin = iBX3;
        layoutParams4.topMargin = iBX3;
        eqn4.setLayoutParams(layoutParams4);
        eqn4.setBackground(com.bytedance.sdk.openadsdk.utils.Kg.bg(context, "tt_detail_video_btn_bg"));
        eqn4.setScaleType(android.widget.ImageView.ScaleType.CENTER);
        eqn4.setImageDrawable(com.bytedance.sdk.openadsdk.utils.Kg.bg(context, "tt_close_move_detail"));
        addView(eqn4);
        com.bytedance.sdk.openadsdk.core.zx.Kg kg2 = new com.bytedance.sdk.openadsdk.core.zx.Kg(context);
        kg2.setId(com.bytedance.sdk.openadsdk.utils.Ta.qSG);
        android.widget.RelativeLayout.LayoutParams layoutParams5 = new android.widget.RelativeLayout.LayoutParams(-1, -2);
        layoutParams5.addRule(9);
        layoutParams5.addRule(20);
        layoutParams5.addRule(10);
        kg2.setLayoutParams(layoutParams5);
        kg2.setBackground(com.bytedance.sdk.openadsdk.utils.Kg.bg(context, "tt_video_black_desc_gradient"));
        kg2.setEllipsize(android.text.TextUtils.TruncateAt.END);
        kg2.setMaxLines(2);
        int iBX4 = com.bytedance.sdk.openadsdk.utils.ZQc.bX(context, 15.0f);
        kg2.setPadding(iBX4, com.bytedance.sdk.openadsdk.utils.ZQc.bX(context, 14.0f), iBX4, 0);
        kg2.setSingleLine(false);
        kg2.setTextColor(-1);
        kg2.setTextSize(2, 17.0f);
        kg2.setVisibility(8);
        addView(kg2);
        com.bytedance.sdk.openadsdk.core.zx.iR iRVar2 = new com.bytedance.sdk.openadsdk.core.zx.iR(context);
        iRVar2.setId(com.bytedance.sdk.openadsdk.utils.Ta.wq);
        android.widget.RelativeLayout.LayoutParams layoutParams6 = new android.widget.RelativeLayout.LayoutParams(-1, -2);
        layoutParams6.addRule(10);
        iRVar2.setLayoutParams(layoutParams6);
        iRVar2.setBackground(com.bytedance.sdk.openadsdk.utils.Kg.bg(context, "tt_video_black_desc_gradient"));
        iRVar2.setGravity(16);
        iRVar2.setVisibility(8);
        addView(iRVar2);
        com.bytedance.sdk.openadsdk.core.zx.eqN eqn5 = new com.bytedance.sdk.openadsdk.core.zx.eqN(context);
        eqn5.setId(com.bytedance.sdk.openadsdk.utils.Ta.GR);
        android.widget.RelativeLayout.LayoutParams layoutParams7 = new android.widget.RelativeLayout.LayoutParams(-2, -1);
        layoutParams7.addRule(15);
        int iBX5 = com.bytedance.sdk.openadsdk.utils.ZQc.bX(context, 12.0f);
        layoutParams7.leftMargin = iBX5;
        layoutParams7.setMarginStart(iBX5);
        eqn5.setLayoutParams(layoutParams7);
        eqn5.setScaleType(android.widget.ImageView.ScaleType.CENTER);
        eqn5.setImageDrawable(com.bytedance.sdk.openadsdk.utils.Kg.bg(context, "tt_leftbackbutton_titlebar_photo_preview"));
        iRVar2.addView(eqn5);
        com.bytedance.sdk.openadsdk.core.zx.Kg kg3 = new com.bytedance.sdk.openadsdk.core.zx.Kg(context);
        kg3.setId(com.bytedance.sdk.openadsdk.utils.Ta.Gih);
        android.widget.RelativeLayout.LayoutParams layoutParams8 = new android.widget.RelativeLayout.LayoutParams(-2, -1);
        layoutParams8.addRule(15);
        int iBX6 = com.bytedance.sdk.openadsdk.utils.ZQc.bX(context, 16.0f);
        layoutParams8.leftMargin = iBX6;
        layoutParams8.rightMargin = iBX;
        layoutParams8.setMarginStart(iBX6);
        layoutParams8.setMarginEnd(iBX);
        layoutParams8.addRule(17, com.bytedance.sdk.openadsdk.utils.Ta.GR);
        layoutParams8.addRule(0, com.bytedance.sdk.openadsdk.utils.Ta.JaB);
        layoutParams8.addRule(1, com.bytedance.sdk.openadsdk.utils.Ta.GR);
        layoutParams8.addRule(16, com.bytedance.sdk.openadsdk.utils.Ta.JaB);
        kg3.setLayoutParams(layoutParams8);
        kg3.setEllipsize(android.text.TextUtils.TruncateAt.END);
        kg3.setGravity(16);
        kg3.setMaxLines(1);
        kg3.setSingleLine(true);
        kg3.setTextColor(-1);
        kg3.setTextSize(2, 17.0f);
        iRVar2.addView(kg3);
        com.bytedance.sdk.openadsdk.core.zx.zx zxVar2 = new com.bytedance.sdk.openadsdk.core.zx.zx(context);
        zxVar2.setId(com.bytedance.sdk.openadsdk.utils.Ta.JaB);
        android.widget.RelativeLayout.LayoutParams layoutParams9 = new android.widget.RelativeLayout.LayoutParams(-2, -2);
        layoutParams9.addRule(21);
        layoutParams9.addRule(11);
        int iBX7 = com.bytedance.sdk.openadsdk.utils.ZQc.bX(context, 14.0f);
        layoutParams9.rightMargin = iBX7;
        layoutParams9.setMarginEnd(iBX7);
        zxVar2.setLayoutParams(layoutParams9);
        zxVar2.setGravity(16);
        zxVar2.setOrientation(1);
        iRVar2.addView(zxVar2);
        com.bytedance.sdk.openadsdk.core.zx.Kg kg4 = new com.bytedance.sdk.openadsdk.core.zx.Kg(context);
        kg4.setId(com.bytedance.sdk.openadsdk.utils.Ta.gJ);
        android.widget.LinearLayout.LayoutParams layoutParams10 = new android.widget.LinearLayout.LayoutParams(-2, -2);
        layoutParams10.gravity = 1;
        kg4.setLayoutParams(layoutParams10);
        kg4.setGravity(16);
        kg4.setMaxLines(1);
        kg4.setSingleLine(true);
        kg4.setTextColor(-1);
        kg4.setTextSize(2, 12.0f);
        zxVar2.addView(kg4);
        com.bytedance.sdk.openadsdk.core.zx.zx zxVar3 = new com.bytedance.sdk.openadsdk.core.zx.zx(context);
        zxVar3.setId(com.bytedance.sdk.openadsdk.utils.Ta.DCn);
        android.widget.RelativeLayout.LayoutParams layoutParams11 = new android.widget.RelativeLayout.LayoutParams(-2, com.bytedance.sdk.openadsdk.utils.ZQc.bX(context, 40.0f));
        layoutParams11.addRule(12);
        layoutParams11.addRule(21);
        layoutParams11.addRule(11);
        zxVar3.setLayoutParams(layoutParams11);
        zxVar3.setGravity(16);
        zxVar3.setOrientation(0);
        zxVar3.setVisibility(8);
        addView(zxVar3);
        com.bytedance.sdk.openadsdk.core.zx.Kg kg5 = new com.bytedance.sdk.openadsdk.core.zx.Kg(context);
        kg5.setId(com.bytedance.sdk.openadsdk.utils.Ta.Fx);
        android.widget.LinearLayout.LayoutParams layoutParams12 = new android.widget.LinearLayout.LayoutParams(-2, -2);
        layoutParams12.leftMargin = iBX6;
        layoutParams12.rightMargin = iBX5;
        layoutParams12.setMarginEnd(iBX5);
        layoutParams12.setMarginStart(iBX6);
        kg5.setLayoutParams(layoutParams12);
        kg5.setText(com.bytedance.sdk.component.utils.Fy.bg(context, "tt_00_00"));
        kg5.setTextColor(-1);
        kg5.setTextSize(2, 10.0f);
        zxVar3.addView(kg5);
        android.widget.SeekBar seekBar = new android.widget.SeekBar(context);
        seekBar.setId(com.bytedance.sdk.openadsdk.utils.Ta.JMw);
        android.widget.LinearLayout.LayoutParams layoutParams13 = new android.widget.LinearLayout.LayoutParams(0, com.bytedance.sdk.openadsdk.utils.ZQc.bX(context, 5.0f));
        layoutParams13.gravity = 16;
        seekBar.setLayoutParams(layoutParams13);
        seekBar.setMax(100);
        seekBar.setPadding(0, 0, 0, 0);
        seekBar.setProgressDrawable(com.bytedance.sdk.openadsdk.utils.Kg.bg(context, "tt_seek_progress"));
        seekBar.setThumb(com.bytedance.sdk.openadsdk.utils.Kg.bg(context, "tt_seek_thumb"));
        seekBar.setThumbOffset(0);
        zxVar3.addView(seekBar);
        com.bytedance.sdk.openadsdk.core.zx.Kg kg6 = new com.bytedance.sdk.openadsdk.core.zx.Kg(context);
        kg6.setId(com.bytedance.sdk.openadsdk.utils.Ta.VHL);
        android.widget.LinearLayout.LayoutParams layoutParams14 = new android.widget.LinearLayout.LayoutParams(-2, -2);
        layoutParams14.leftMargin = iBX5;
        layoutParams14.rightMargin = iBX6;
        layoutParams14.setMarginEnd(iBX6);
        layoutParams14.setMarginStart(iBX5);
        kg6.setLayoutParams(layoutParams14);
        kg6.setText(com.bytedance.sdk.component.utils.Fy.bg(context, "tt_00_00"));
        kg6.setTextColor(-1);
        kg6.setTextSize(2, 10.0f);
        zxVar3.addView(kg6);
        com.bytedance.sdk.openadsdk.core.zx.eqN eqn6 = new com.bytedance.sdk.openadsdk.core.zx.eqN(context);
        eqn6.setId(com.bytedance.sdk.openadsdk.utils.Ta.dtS);
        eqn6.setLayoutParams(new android.widget.LinearLayout.LayoutParams(-2, -1));
        eqn6.setPadding(iBX6, 0, iBX6, 0);
        eqn6.setScaleType(android.widget.ImageView.ScaleType.CENTER);
        eqn6.setVisibility(8);
        eqn6.setImageDrawable(com.bytedance.sdk.component.utils.Fy.bX(context, "tt_enlarge_video"));
        zxVar3.addView(eqn6);
        com.bytedance.sdk.openadsdk.Ta.PX px = new com.bytedance.sdk.openadsdk.Ta.PX(context);
        px.setId(com.bytedance.sdk.openadsdk.utils.Ta.ovC);
        px.setLayoutParams(new android.widget.RelativeLayout.LayoutParams(-1, -1));
        addView(px);
        com.bytedance.sdk.openadsdk.core.zx.Kg kg7 = new com.bytedance.sdk.openadsdk.core.zx.Kg(context);
        kg7.setId(com.bytedance.sdk.openadsdk.utils.Ta.fE);
        android.widget.RelativeLayout.LayoutParams layoutParams15 = new android.widget.RelativeLayout.LayoutParams(-2, -2);
        layoutParams15.leftMargin = iBX5;
        layoutParams15.addRule(9);
        layoutParams15.addRule(20);
        kg7.setLayoutParams(layoutParams15);
        kg7.setBackgroundColor(android.graphics.Color.parseColor("#00000000"));
        kg7.setText("close");
        kg7.setMinHeight(com.bytedance.sdk.openadsdk.utils.ZQc.bX(context, 44.0f));
        kg7.setCompoundDrawablesWithIntrinsicBounds(com.bytedance.sdk.openadsdk.utils.Kg.bg(context, "tt_shadow_btn_back"), (android.graphics.drawable.Drawable) null, (android.graphics.drawable.Drawable) null, (android.graphics.drawable.Drawable) null);
        addView(kg7);
    }
}
