package com.bytedance.sdk.component.adexpress.bX;

/* JADX INFO: loaded from: classes3.dex */
public class bg {
    public static android.view.View bg(android.content.Context context) {
        android.widget.LinearLayout linearLayout = new android.widget.LinearLayout(context);
        linearLayout.setLayoutParams(new android.widget.LinearLayout.LayoutParams(-1, -1));
        linearLayout.setGravity(81);
        android.widget.LinearLayout linearLayout2 = new android.widget.LinearLayout(context);
        linearLayout2.setLayoutParams(new android.widget.LinearLayout.LayoutParams(com.bytedance.sdk.component.utils.Ja.bg(context, 46.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 32.0f)));
        linearLayout2.setBackground(com.bytedance.sdk.component.adexpress.eqN.WR.bg(0, java.lang.Integer.valueOf(android.graphics.Color.parseColor("#99000000")), new int[]{com.bytedance.sdk.component.utils.Ja.bg(context, 40.0f)}, null, java.lang.Integer.valueOf(com.bytedance.sdk.component.utils.Ja.bg(context, 1.0f)), java.lang.Integer.valueOf(android.graphics.Color.parseColor("#88FFFFFF"))));
        linearLayout2.setGravity(17);
        linearLayout2.setOrientation(1);
        android.widget.ImageView imageView = new android.widget.ImageView(context);
        imageView.setLayoutParams(new android.widget.LinearLayout.LayoutParams(-2, -2));
        imageView.setBackground(com.bytedance.sdk.component.utils.Fy.bX(context, "tt_splash_slide_up_10"));
        linearLayout2.addView(imageView);
        linearLayout.addView(linearLayout2);
        return linearLayout;
    }

    public static android.view.View IL(android.content.Context context) {
        android.widget.LinearLayout linearLayout = new android.widget.LinearLayout(context);
        linearLayout.setLayoutParams(new android.widget.LinearLayout.LayoutParams(-1, -1));
        linearLayout.setGravity(81);
        android.widget.LinearLayout linearLayout2 = new android.widget.LinearLayout(context);
        linearLayout2.setLayoutParams(new android.widget.LinearLayout.LayoutParams(-1, com.bytedance.sdk.component.utils.Ja.bg(context, 100.0f)));
        linearLayout2.setGravity(17);
        linearLayout2.setOrientation(1);
        android.widget.FrameLayout frameLayout = new android.widget.FrameLayout(context);
        frameLayout.setLayoutParams(new android.widget.LinearLayout.LayoutParams(-1, -2));
        android.widget.ImageView imageView = new android.widget.ImageView(context);
        imageView.setId(2097610751);
        android.widget.FrameLayout.LayoutParams layoutParams = new android.widget.FrameLayout.LayoutParams(com.bytedance.sdk.component.utils.Ja.bg(context, 19.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 15.0f));
        layoutParams.gravity = 1;
        imageView.setLayoutParams(layoutParams);
        imageView.setScaleType(android.widget.ImageView.ScaleType.FIT_XY);
        imageView.setImageDrawable(com.bytedance.sdk.component.utils.Fy.bX(context, "tt_white_slide_up"));
        android.widget.ImageView imageView2 = new android.widget.ImageView(context);
        imageView2.setId(2097610750);
        android.widget.FrameLayout.LayoutParams layoutParams2 = new android.widget.FrameLayout.LayoutParams(com.bytedance.sdk.component.utils.Ja.bg(context, 19.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 15.0f));
        layoutParams2.gravity = 1;
        layoutParams2.topMargin = com.bytedance.sdk.component.utils.Ja.bg(context, 7.0f);
        imageView2.setLayoutParams(layoutParams2);
        imageView2.setScaleType(android.widget.ImageView.ScaleType.FIT_XY);
        imageView2.setImageDrawable(com.bytedance.sdk.component.utils.Fy.bX(context, "tt_white_slide_up"));
        android.widget.ImageView imageView3 = new android.widget.ImageView(context);
        imageView3.setId(2097610749);
        android.widget.FrameLayout.LayoutParams layoutParams3 = new android.widget.FrameLayout.LayoutParams(com.bytedance.sdk.component.utils.Ja.bg(context, 19.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 15.0f));
        layoutParams3.gravity = 1;
        layoutParams3.topMargin = com.bytedance.sdk.component.utils.Ja.bg(context, 14.0f);
        imageView3.setLayoutParams(layoutParams3);
        imageView3.setScaleType(android.widget.ImageView.ScaleType.FIT_XY);
        imageView3.setImageDrawable(com.bytedance.sdk.component.utils.Fy.bX(context, "tt_white_slide_up"));
        frameLayout.addView(imageView);
        frameLayout.addView(imageView2);
        frameLayout.addView(imageView3);
        linearLayout2.addView(frameLayout);
        android.view.View view = new android.view.View(context);
        view.setLayoutParams(new android.widget.LinearLayout.LayoutParams(-1, 0, 1.0f));
        linearLayout2.addView(view);
        android.widget.TextView textView = new android.widget.TextView(context);
        textView.setId(2097610748);
        android.widget.LinearLayout.LayoutParams layoutParams4 = new android.widget.LinearLayout.LayoutParams(-1, -2);
        layoutParams4.setMargins(0, 0, 0, com.bytedance.sdk.component.utils.Ja.bg(context, 5.0f));
        textView.setLayoutParams(layoutParams4);
        textView.setGravity(1);
        textView.setTextColor(-1);
        textView.setTextSize(1, 14.0f);
        linearLayout2.addView(textView);
        linearLayout.addView(linearLayout2);
        return linearLayout;
    }

    public static android.view.View bX(android.content.Context context) {
        android.widget.LinearLayout linearLayout = new android.widget.LinearLayout(context);
        linearLayout.setLayoutParams(new android.widget.LinearLayout.LayoutParams(-2, -2));
        linearLayout.setBackground(com.bytedance.sdk.component.utils.Fy.bX(context, "tt_splash_unlock_btn_bg"));
        linearLayout.setPadding(com.bytedance.sdk.component.utils.Ja.bg(context, 38.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 20.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 38.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 20.0f));
        linearLayout.setGravity(17);
        linearLayout.setOrientation(0);
        android.widget.ImageView imageView = new android.widget.ImageView(context);
        imageView.setLayoutParams(new android.widget.LinearLayout.LayoutParams(-2, -2));
        imageView.setBackground(com.bytedance.sdk.component.utils.Fy.bX(context, "tt_splash_shake_hand"));
        android.widget.TextView textView = new android.widget.TextView(context);
        textView.setId(2097610747);
        android.widget.LinearLayout.LayoutParams layoutParams = new android.widget.LinearLayout.LayoutParams(-2, -2);
        layoutParams.setMargins(com.bytedance.sdk.component.utils.Ja.bg(context, 8.0f), 0, 0, 0);
        textView.setLayoutParams(layoutParams);
        textView.setTextSize(2, 17.0f);
        textView.setTextColor(-1);
        linearLayout.addView(imageView);
        linearLayout.addView(textView);
        return linearLayout;
    }

    public static android.view.View eqN(android.content.Context context) {
        android.widget.RelativeLayout relativeLayout = new android.widget.RelativeLayout(context);
        relativeLayout.setLayoutParams(new android.widget.RelativeLayout.LayoutParams(-2, -2));
        android.widget.RelativeLayout relativeLayout2 = new android.widget.RelativeLayout(context);
        relativeLayout2.setId(2097610746);
        android.widget.RelativeLayout.LayoutParams layoutParams = new android.widget.RelativeLayout.LayoutParams(com.bytedance.sdk.component.utils.Ja.bg(context, 247.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 56.0f));
        layoutParams.addRule(14);
        relativeLayout2.setLayoutParams(layoutParams);
        relativeLayout2.setBackground(com.bytedance.sdk.component.utils.Fy.bX(context, "tt_splash_unlock_btn_bg"));
        android.widget.ImageView imageView = new android.widget.ImageView(context);
        imageView.setId(2097610745);
        android.widget.RelativeLayout.LayoutParams layoutParams2 = new android.widget.RelativeLayout.LayoutParams(com.bytedance.sdk.component.utils.Ja.bg(context, 48.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 48.0f));
        layoutParams2.addRule(20);
        layoutParams2.addRule(15);
        layoutParams2.setMargins(com.bytedance.sdk.component.utils.Ja.bg(context, 4.0f), 0, 0, 0);
        imageView.setLayoutParams(layoutParams2);
        imageView.setImageDrawable(com.bytedance.sdk.component.utils.Fy.bX(context, "tt_splash_unlock_image_go"));
        com.bytedance.sdk.component.adexpress.ldr.PX px = new com.bytedance.sdk.component.adexpress.ldr.PX(context);
        px.setId(2097610744);
        android.widget.RelativeLayout.LayoutParams layoutParams3 = new android.widget.RelativeLayout.LayoutParams(-1, com.bytedance.sdk.component.utils.Ja.bg(context, 24.0f));
        layoutParams3.addRule(15);
        layoutParams3.setMargins(com.bytedance.sdk.component.utils.Ja.bg(context, 12.0f), 0, com.bytedance.sdk.component.utils.Ja.bg(context, 12.0f), 0);
        layoutParams3.addRule(16, 2097610743);
        layoutParams3.addRule(17, 2097610745);
        px.setLayoutParams(layoutParams3);
        android.widget.ImageView imageView2 = new android.widget.ImageView(context);
        imageView2.setId(2097610743);
        android.widget.RelativeLayout.LayoutParams layoutParams4 = new android.widget.RelativeLayout.LayoutParams(com.bytedance.sdk.component.utils.Ja.bg(context, 48.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 48.0f));
        layoutParams4.addRule(21);
        layoutParams4.addRule(15);
        layoutParams4.setMarginStart(com.bytedance.sdk.component.utils.Ja.bg(context, 2.0f));
        layoutParams4.setMarginEnd(com.bytedance.sdk.component.utils.Ja.bg(context, 4.0f));
        imageView2.setLayoutParams(layoutParams4);
        imageView2.setImageDrawable(com.bytedance.sdk.component.utils.Fy.bX(context, "tt_splash_unlock_icon_empty"));
        relativeLayout2.addView(imageView);
        relativeLayout2.addView(px);
        relativeLayout2.addView(imageView2);
        android.widget.TextView textView = new android.widget.TextView(context);
        textView.setId(2097610742);
        android.widget.RelativeLayout.LayoutParams layoutParams5 = new android.widget.RelativeLayout.LayoutParams(-2, -2);
        layoutParams5.addRule(3, 2097610746);
        layoutParams5.addRule(14);
        layoutParams5.setMargins(0, com.bytedance.sdk.component.utils.Ja.bg(context, 12.0f), 0, 0);
        textView.setLayoutParams(layoutParams5);
        textView.setTextColor(-1);
        textView.setShadowLayer(com.bytedance.sdk.component.utils.Ja.bg(context, 3.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 3.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 3.0f), android.graphics.Color.parseColor("#99000000"));
        relativeLayout.addView(relativeLayout2);
        relativeLayout.addView(textView);
        return relativeLayout;
    }

    public static android.view.View zx(android.content.Context context) {
        android.widget.RelativeLayout relativeLayout = new android.widget.RelativeLayout(context);
        relativeLayout.setLayoutParams(new android.widget.RelativeLayout.LayoutParams(-1, -1));
        relativeLayout.setGravity(16);
        relativeLayout.setClipChildren(false);
        android.widget.ImageView imageView = new android.widget.ImageView(context);
        imageView.setId(2097610735);
        android.widget.RelativeLayout.LayoutParams layoutParams = new android.widget.RelativeLayout.LayoutParams(com.bytedance.sdk.component.utils.Ja.bg(context, 36.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 36.0f));
        layoutParams.addRule(14);
        layoutParams.addRule(8, 2097610732);
        layoutParams.setMargins(0, 0, 0, com.bytedance.sdk.component.utils.Ja.bg(context, -24.0f));
        imageView.setLayoutParams(layoutParams);
        imageView.setBackground(com.bytedance.sdk.component.utils.Fy.bX(context, "tt_splash_slide_up_circle"));
        imageView.setAlpha(0.0f);
        android.widget.ImageView imageView2 = new android.widget.ImageView(context);
        imageView2.setId(2097610734);
        android.widget.RelativeLayout.LayoutParams layoutParams2 = new android.widget.RelativeLayout.LayoutParams(com.bytedance.sdk.component.utils.Ja.bg(context, 67.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 51.0f));
        layoutParams2.addRule(14);
        layoutParams2.addRule(1, 2097610732);
        layoutParams2.addRule(8, 2097610732);
        layoutParams2.setMargins(com.bytedance.sdk.component.utils.Ja.bg(context, -7.0f), 0, 0, com.bytedance.sdk.component.utils.Ja.bg(context, -20.0f));
        imageView2.setLayoutParams(layoutParams2);
        imageView2.setBackground(com.bytedance.sdk.component.utils.Fy.bX(context, "tt_splash_slide_up_finger"));
        imageView2.setAlpha(0.0f);
        android.widget.ImageView imageView3 = new android.widget.ImageView(context);
        imageView3.setId(2097610733);
        android.widget.RelativeLayout.LayoutParams layoutParams3 = new android.widget.RelativeLayout.LayoutParams(com.bytedance.sdk.component.utils.Ja.bg(context, 10.0f), 0);
        layoutParams3.addRule(14);
        layoutParams3.addRule(8, 2097610732);
        imageView3.setLayoutParams(layoutParams3);
        imageView3.setBackground(com.bytedance.sdk.component.utils.Fy.bX(context, "tt_splash_slide_up_bg"));
        android.widget.ImageView imageView4 = new android.widget.ImageView(context);
        imageView4.setId(2097610732);
        android.widget.RelativeLayout.LayoutParams layoutParams4 = new android.widget.RelativeLayout.LayoutParams(com.bytedance.sdk.component.utils.Ja.bg(context, 14.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 100.0f));
        layoutParams4.addRule(14);
        imageView4.setLayoutParams(layoutParams4);
        imageView4.setBackground(com.bytedance.sdk.component.utils.Fy.bX(context, "tt_splash_slide_up_arrow"));
        android.widget.TextView textView = new android.widget.TextView(context);
        textView.setId(2097610731);
        android.widget.RelativeLayout.LayoutParams layoutParams5 = new android.widget.RelativeLayout.LayoutParams(-1, -2);
        layoutParams5.addRule(3, 2097610732);
        textView.setLayoutParams(layoutParams5);
        textView.setTextColor(-1);
        textView.setText("wipe up");
        textView.setTextSize(2, 18.0f);
        textView.setShadowLayer(com.bytedance.sdk.component.utils.Ja.bg(context, 4.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 3.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 3.0f), android.graphics.Color.parseColor("#99000000"));
        textView.setGravity(1);
        android.widget.TextView textView2 = new android.widget.TextView(context);
        textView2.setId(2097610730);
        android.widget.RelativeLayout.LayoutParams layoutParams6 = new android.widget.RelativeLayout.LayoutParams(-1, -2);
        layoutParams6.addRule(3, 2097610731);
        textView2.setLayoutParams(layoutParams6);
        textView2.setTextColor(-1);
        textView2.setTextSize(2, 14.0f);
        textView2.setShadowLayer(com.bytedance.sdk.component.utils.Ja.bg(context, 4.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 3.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 3.0f), android.graphics.Color.parseColor("#99000000"));
        textView2.setGravity(1);
        relativeLayout.addView(imageView);
        relativeLayout.addView(imageView2);
        relativeLayout.addView(imageView3);
        relativeLayout.addView(imageView4);
        relativeLayout.addView(textView);
        relativeLayout.addView(textView2);
        return relativeLayout;
    }

    public static android.view.View ldr(android.content.Context context) {
        android.widget.RelativeLayout relativeLayout = new android.widget.RelativeLayout(context);
        relativeLayout.setLayoutParams(new android.widget.RelativeLayout.LayoutParams(-1, -1));
        relativeLayout.setClipChildren(false);
        relativeLayout.setClipToPadding(false);
        relativeLayout.setGravity(16);
        android.widget.RelativeLayout relativeLayout2 = new android.widget.RelativeLayout(context);
        relativeLayout2.setId(2097610729);
        android.widget.RelativeLayout.LayoutParams layoutParams = new android.widget.RelativeLayout.LayoutParams(-2, -1);
        layoutParams.addRule(13);
        layoutParams.setMargins(0, 0, 0, 0);
        relativeLayout2.setLayoutParams(layoutParams);
        relativeLayout2.setClipChildren(false);
        relativeLayout2.setClipToPadding(false);
        relativeLayout2.setPadding(com.bytedance.sdk.component.utils.Ja.bg(context, 60.0f), 0, 0, 0);
        relativeLayout.addView(relativeLayout2);
        android.widget.ImageView imageView = new android.widget.ImageView(context);
        imageView.setId(2097610735);
        android.widget.RelativeLayout.LayoutParams layoutParams2 = new android.widget.RelativeLayout.LayoutParams(com.bytedance.sdk.component.utils.Ja.bg(context, 80.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 80.0f));
        layoutParams2.addRule(9);
        layoutParams2.addRule(12);
        layoutParams2.setMargins(0, 0, 0, -com.bytedance.sdk.component.utils.Ja.bg(context, 40.0f));
        imageView.setLayoutParams(layoutParams2);
        imageView.setAlpha(0);
        imageView.setBackground(com.bytedance.sdk.component.utils.Fy.bX(context, "tt_splash_slide_up_circle"));
        relativeLayout2.addView(imageView);
        android.widget.ImageView imageView2 = new android.widget.ImageView(context);
        imageView2.setId(2097610733);
        android.widget.RelativeLayout.LayoutParams layoutParams3 = new android.widget.RelativeLayout.LayoutParams(com.bytedance.sdk.component.utils.Ja.bg(context, 16.0f), 0);
        layoutParams3.addRule(9);
        layoutParams3.addRule(12);
        layoutParams3.setMargins(com.bytedance.sdk.component.utils.Ja.bg(context, 36.0f), 0, 0, 0);
        imageView2.setLayoutParams(layoutParams3);
        imageView2.setBackground(com.bytedance.sdk.component.utils.Fy.bX(context, "tt_splash_slide_up_bg"));
        relativeLayout2.addView(imageView2);
        android.widget.ImageView imageView3 = new android.widget.ImageView(context);
        imageView3.setId(2097610734);
        android.widget.RelativeLayout.LayoutParams layoutParams4 = new android.widget.RelativeLayout.LayoutParams(com.bytedance.sdk.component.utils.Ja.bg(context, 160.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 120.0f));
        layoutParams4.addRule(12);
        layoutParams4.setMargins(com.bytedance.sdk.component.utils.Ja.bg(context, 35.0f), 0, 0, -com.bytedance.sdk.component.utils.Ja.bg(context, 40.0f));
        imageView3.setLayoutParams(layoutParams4);
        imageView3.setAlpha(0);
        imageView3.setBackground(com.bytedance.sdk.component.utils.Fy.bX(context, "tt_splash_slide_up_finger"));
        relativeLayout2.addView(imageView3);
        android.widget.TextView textView = new android.widget.TextView(context);
        textView.setId(2097610730);
        android.widget.RelativeLayout.LayoutParams layoutParams5 = new android.widget.RelativeLayout.LayoutParams(-1, com.bytedance.sdk.component.utils.Ja.bg(context, 20.0f));
        layoutParams5.addRule(12);
        layoutParams5.setMargins(0, 0, 0, -com.bytedance.sdk.component.utils.Ja.bg(context, 95.0f));
        textView.setLayoutParams(layoutParams5);
        textView.setGravity(1);
        textView.setShadowLayer(4.0f, 3.0f, 3.0f, android.graphics.Color.parseColor("#99000000"));
        textView.setTextColor(-1);
        textView.setTextSize(1, 14.0f);
        relativeLayout.addView(textView);
        return relativeLayout;
    }

    public static android.view.View iR(android.content.Context context) {
        android.widget.LinearLayout linearLayout = new android.widget.LinearLayout(context);
        linearLayout.setLayoutParams(new android.widget.LinearLayout.LayoutParams(-2, -2));
        linearLayout.setOrientation(1);
        android.widget.TextView textView = new android.widget.TextView(context);
        textView.setId(2097610728);
        android.widget.LinearLayout.LayoutParams layoutParams = new android.widget.LinearLayout.LayoutParams(-2, -2);
        layoutParams.gravity = 17;
        layoutParams.setMargins(0, com.bytedance.sdk.component.utils.Ja.bg(context, 12.0f), 0, 0);
        textView.setLayoutParams(layoutParams);
        textView.setVisibility(4);
        linearLayout.addView(textView);
        android.widget.LinearLayout linearLayout2 = new android.widget.LinearLayout(context);
        linearLayout2.setId(2097610727);
        android.widget.LinearLayout.LayoutParams layoutParams2 = new android.widget.LinearLayout.LayoutParams(com.bytedance.sdk.component.utils.Ja.bg(context, 110.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 110.0f));
        layoutParams2.gravity = 17;
        linearLayout2.setLayoutParams(layoutParams2);
        linearLayout2.setGravity(17);
        linearLayout2.setOrientation(1);
        linearLayout.addView(linearLayout2);
        android.widget.TextView textView2 = new android.widget.TextView(context);
        textView2.setId(2097610726);
        textView2.setLayoutParams(new android.widget.LinearLayout.LayoutParams(-2, -2));
        textView2.setVisibility(4);
        textView2.setTextSize(2, 14.0f);
        linearLayout2.addView(textView2);
        android.widget.ImageView imageView = new android.widget.ImageView(context);
        imageView.setId(2097610725);
        imageView.setLayoutParams(new android.widget.LinearLayout.LayoutParams(com.bytedance.sdk.component.utils.Ja.bg(context, 60.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 60.0f)));
        imageView.setImageDrawable(com.bytedance.sdk.component.utils.Fy.bX(context, "tt_splash_rock"));
        linearLayout2.addView(imageView);
        android.widget.TextView textView3 = new android.widget.TextView(context);
        textView3.setId(2097610724);
        textView3.setLayoutParams(new android.widget.LinearLayout.LayoutParams(-2, -2));
        textView3.setSingleLine(true);
        textView3.setText("Shake it");
        textView3.setTextColor(-1);
        textView3.setTextSize(2, 14.0f);
        linearLayout2.addView(textView3);
        android.widget.TextView textView4 = new android.widget.TextView(context);
        textView4.setId(2097610723);
        android.widget.LinearLayout.LayoutParams layoutParams3 = new android.widget.LinearLayout.LayoutParams(-2, -2);
        layoutParams3.gravity = 17;
        layoutParams3.setMargins(0, com.bytedance.sdk.component.utils.Ja.bg(context, 12.0f), 0, 0);
        textView4.setLayoutParams(layoutParams3);
        textView4.setShadowLayer(4.0f, 3.0f, 3.0f, android.graphics.Color.parseColor("#99000000"));
        textView4.setText("Go to details page or third-party application");
        textView4.setTextColor(-1);
        linearLayout.addView(textView4);
        return linearLayout;
    }

    public static android.view.View Kg(android.content.Context context) {
        android.widget.LinearLayout linearLayout = new android.widget.LinearLayout(context);
        linearLayout.setLayoutParams(new android.widget.LinearLayout.LayoutParams(-2, -2));
        linearLayout.setOrientation(1);
        android.widget.TextView textView = new android.widget.TextView(context);
        textView.setId(2097610726);
        android.widget.LinearLayout.LayoutParams layoutParams = new android.widget.LinearLayout.LayoutParams(-2, -2);
        layoutParams.gravity = 17;
        layoutParams.setMargins(0, com.bytedance.sdk.component.utils.Ja.bg(context, 12.0f), 0, 0);
        textView.setLayoutParams(layoutParams);
        textView.setVisibility(4);
        textView.setTextSize(1, 18.0f);
        linearLayout.addView(textView);
        android.widget.TextView textView2 = new android.widget.TextView(context);
        textView2.setId(2097610728);
        android.widget.LinearLayout.LayoutParams layoutParams2 = new android.widget.LinearLayout.LayoutParams(-2, -2);
        layoutParams2.gravity = 17;
        textView2.setLayoutParams(layoutParams2);
        textView2.setVisibility(4);
        textView2.setTextSize(1, 14.0f);
        linearLayout.addView(textView2);
        android.widget.LinearLayout linearLayout2 = new android.widget.LinearLayout(context);
        linearLayout2.setId(2097610727);
        android.widget.LinearLayout.LayoutParams layoutParams3 = new android.widget.LinearLayout.LayoutParams(-2, -2);
        layoutParams3.gravity = 17;
        linearLayout2.setLayoutParams(layoutParams3);
        linearLayout2.setGravity(17);
        linearLayout2.setOrientation(1);
        linearLayout.addView(linearLayout2);
        android.widget.ImageView imageView = new android.widget.ImageView(context);
        imageView.setId(2097610725);
        imageView.setLayoutParams(new android.widget.LinearLayout.LayoutParams(com.bytedance.sdk.component.utils.Ja.bg(context, 60.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 60.0f)));
        imageView.setImageDrawable(com.bytedance.sdk.component.utils.Fy.bX(context, "tt_splash_rock"));
        linearLayout2.addView(imageView);
        android.widget.TextView textView3 = new android.widget.TextView(context);
        textView3.setId(2097610724);
        android.widget.LinearLayout.LayoutParams layoutParams4 = new android.widget.LinearLayout.LayoutParams(-2, -2);
        layoutParams4.gravity = 17;
        layoutParams4.setMargins(0, com.bytedance.sdk.component.utils.Ja.bg(context, 12.0f), 0, 0);
        textView3.setLayoutParams(layoutParams4);
        textView3.setSingleLine(true);
        textView3.setText(context.getString(com.bytedance.sdk.component.utils.Fy.IL(context, "tt_splash_rock_top_text")));
        textView3.setTextColor(-1);
        textView3.setShadowLayer(4.0f, 3.0f, 3.0f, android.graphics.Color.parseColor("#99000000"));
        textView3.setTextSize(1, 18.0f);
        linearLayout.addView(textView3);
        android.widget.TextView textView4 = new android.widget.TextView(context);
        textView4.setId(2097610723);
        android.widget.LinearLayout.LayoutParams layoutParams5 = new android.widget.LinearLayout.LayoutParams(-2, -2);
        layoutParams5.gravity = 17;
        layoutParams5.setMargins(0, com.bytedance.sdk.component.utils.Ja.bg(context, 12.0f), 0, 0);
        textView4.setLayoutParams(layoutParams5);
        textView4.setShadowLayer(4.0f, 3.0f, 3.0f, android.graphics.Color.parseColor("#99000000"));
        textView4.setTextSize(1, 14.0f);
        textView4.setText(context.getString(com.bytedance.sdk.component.utils.Fy.IL(context, "tt_splash_rock_text")));
        textView4.setTextColor(-1);
        linearLayout.addView(textView4);
        return linearLayout;
    }

    public static android.view.View WR(android.content.Context context) {
        android.widget.LinearLayout linearLayout = new android.widget.LinearLayout(context);
        linearLayout.setLayoutParams(new android.widget.LinearLayout.LayoutParams(-2, -2));
        linearLayout.setOrientation(1);
        android.widget.LinearLayout linearLayout2 = new android.widget.LinearLayout(context);
        linearLayout2.setId(2097610722);
        android.widget.LinearLayout.LayoutParams layoutParams = new android.widget.LinearLayout.LayoutParams(com.bytedance.sdk.component.utils.Ja.bg(context, 110.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 110.0f));
        layoutParams.gravity = 17;
        layoutParams.setMargins(0, 0, 0, com.bytedance.sdk.component.utils.Ja.bg(context, 4.0f));
        linearLayout2.setLayoutParams(layoutParams);
        linearLayout2.setGravity(17);
        linearLayout2.setOrientation(1);
        linearLayout2.setVisibility(0);
        linearLayout.addView(linearLayout2);
        com.bytedance.adsdk.IL.ldr ldrVar = new com.bytedance.adsdk.IL.ldr(context);
        ldrVar.setId(2097610706);
        ldrVar.setLayoutParams(new android.widget.LinearLayout.LayoutParams(com.bytedance.sdk.component.utils.Ja.bg(context, 100.0f), com.bytedance.sdk.component.utils.Ja.bg(context, 100.0f)));
        linearLayout2.addView(ldrVar);
        android.widget.TextView textView = new android.widget.TextView(context);
        textView.setId(2097610719);
        android.widget.LinearLayout.LayoutParams layoutParams2 = new android.widget.LinearLayout.LayoutParams(-2, -2);
        layoutParams2.gravity = 17;
        textView.setLayoutParams(layoutParams2);
        textView.setSingleLine(true);
        textView.setText(context.getString(com.bytedance.sdk.component.utils.Fy.IL(context, "tt_splash_wriggle_top_text")));
        textView.setTextColor(-1);
        textView.setTextSize(1, 18.0f);
        textView.setTypeface(null, 1);
        textView.setShadowLayer(2.0f, 0.0f, 0.5f, android.graphics.Color.parseColor("#4D000000"));
        linearLayout.addView(textView);
        android.widget.TextView textView2 = new android.widget.TextView(context);
        textView2.setId(2097610718);
        android.widget.LinearLayout.LayoutParams layoutParams3 = new android.widget.LinearLayout.LayoutParams(-2, -2);
        layoutParams3.gravity = 17;
        textView2.setLayoutParams(layoutParams3);
        textView2.setSingleLine(true);
        textView2.setText(context.getString(com.bytedance.sdk.component.utils.Fy.IL(context, "tt_splash_wriggle_text")));
        textView2.setTextColor(-1);
        textView2.setTextSize(1, 14.0f);
        textView2.setTypeface(null, 1);
        textView2.setShadowLayer(2.0f, 0.0f, 0.5f, android.graphics.Color.parseColor("#4D000000"));
        linearLayout.addView(textView2);
        return linearLayout;
    }
}
