package com.android.billingclient.api;

/* JADX INFO: compiled from: com.android.billingclient:billing@@8.0.0 */
/* JADX INFO: loaded from: classes3.dex */
final class zzcj {
    static final com.android.billingclient.api.BillingResult zzA;
    static final com.android.billingclient.api.BillingResult zzB;
    static final com.android.billingclient.api.BillingResult zzC;
    static final com.android.billingclient.api.BillingResult zzD;
    static final com.android.billingclient.api.BillingResult zzE;
    static final com.android.billingclient.api.BillingResult zzF;
    public static final /* synthetic */ int zzG = 0;
    static final com.android.billingclient.api.BillingResult zza;
    static final com.android.billingclient.api.BillingResult zzb;
    static final com.android.billingclient.api.BillingResult zzc;
    static final com.android.billingclient.api.BillingResult zzd;
    static final com.android.billingclient.api.BillingResult zze;
    static final com.android.billingclient.api.BillingResult zzf;
    static final com.android.billingclient.api.BillingResult zzg;
    static final com.android.billingclient.api.BillingResult zzh;
    static final com.android.billingclient.api.BillingResult zzi;
    static final com.android.billingclient.api.BillingResult zzj;
    static final com.android.billingclient.api.BillingResult zzk;
    static final com.android.billingclient.api.BillingResult zzl;
    static final com.android.billingclient.api.BillingResult zzm;
    static final com.android.billingclient.api.BillingResult zzn;
    static final com.android.billingclient.api.BillingResult zzo;
    static final com.android.billingclient.api.BillingResult zzp;
    static final com.android.billingclient.api.BillingResult zzq;
    static final com.android.billingclient.api.BillingResult zzr;
    static final com.android.billingclient.api.BillingResult zzs;
    static final com.android.billingclient.api.BillingResult zzt;
    static final com.android.billingclient.api.BillingResult zzu;
    static final com.android.billingclient.api.BillingResult zzv;
    static final com.android.billingclient.api.BillingResult zzw;
    static final com.android.billingclient.api.BillingResult zzx;
    static final com.android.billingclient.api.BillingResult zzy;
    static final com.android.billingclient.api.BillingResult zzz;

    static {
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder.setResponseCode(3);
        builderNewBuilder.setDebugMessage("Google Play In-app Billing API version is less than 3");
        builderNewBuilder.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder2 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder2.setResponseCode(3);
        builderNewBuilder2.setDebugMessage("Google Play In-app Billing API version is less than 9");
        zza = builderNewBuilder2.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder3 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder3.setResponseCode(3);
        builderNewBuilder3.setDebugMessage("Billing service unavailable on device.");
        zzb = builderNewBuilder3.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder4 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder4.setResponseCode(2);
        builderNewBuilder4.setDebugMessage("Billing service unavailable on device.");
        zzc = builderNewBuilder4.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder5 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder5.setResponseCode(5);
        builderNewBuilder5.setDebugMessage("Client is already in the process of connecting to billing service.");
        zzd = builderNewBuilder5.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder6 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder6.setResponseCode(5);
        builderNewBuilder6.setDebugMessage("The list of SKUs can't be empty.");
        builderNewBuilder6.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder7 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder7.setResponseCode(5);
        builderNewBuilder7.setDebugMessage("SKU type can't be empty.");
        builderNewBuilder7.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder8 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder8.setResponseCode(5);
        builderNewBuilder8.setDebugMessage("Product type can't be empty.");
        zze = builderNewBuilder8.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder9 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder9.setResponseCode(-2);
        builderNewBuilder9.setDebugMessage("Client does not support extra params.");
        zzf = builderNewBuilder9.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder10 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder10.setResponseCode(5);
        builderNewBuilder10.setDebugMessage("Invalid purchase token.");
        zzg = builderNewBuilder10.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder11 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder11.setResponseCode(6);
        builderNewBuilder11.setDebugMessage("An internal error occurred.");
        zzh = builderNewBuilder11.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder12 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder12.setResponseCode(5);
        builderNewBuilder12.setDebugMessage("SKU can't be null.");
        builderNewBuilder12.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder13 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder13.setResponseCode(0);
        zzi = builderNewBuilder13.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder14 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder14.setResponseCode(-1);
        builderNewBuilder14.setDebugMessage("Service connection is disconnected.");
        zzj = builderNewBuilder14.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder15 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder15.setResponseCode(2);
        builderNewBuilder15.setDebugMessage("Timeout communicating with service.");
        zzk = builderNewBuilder15.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder16 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder16.setResponseCode(-2);
        builderNewBuilder16.setDebugMessage("Client does not support subscriptions.");
        zzl = builderNewBuilder16.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder17 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder17.setResponseCode(-2);
        builderNewBuilder17.setDebugMessage("Client does not support subscriptions update.");
        zzm = builderNewBuilder17.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder18 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder18.setResponseCode(-2);
        builderNewBuilder18.setDebugMessage("Client does not support get purchase history.");
        builderNewBuilder18.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder19 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder19.setResponseCode(-2);
        builderNewBuilder19.setDebugMessage("Client does not support price change confirmation.");
        zzn = builderNewBuilder19.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder20 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder20.setResponseCode(-2);
        builderNewBuilder20.setDebugMessage("Play Store version installed does not support cross selling products.");
        zzo = builderNewBuilder20.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder21 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder21.setResponseCode(-2);
        builderNewBuilder21.setDebugMessage("Client does not support multi-item purchases.");
        zzp = builderNewBuilder21.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder22 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder22.setResponseCode(-2);
        builderNewBuilder22.setDebugMessage("Client does not support offer_id_token.");
        zzq = builderNewBuilder22.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder23 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder23.setResponseCode(-2);
        builderNewBuilder23.setDebugMessage("Client does not support ProductDetails.");
        zzr = builderNewBuilder23.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder24 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder24.setResponseCode(-2);
        builderNewBuilder24.setDebugMessage("Client does not support in-app messages.");
        zzs = builderNewBuilder24.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder25 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder25.setResponseCode(-2);
        builderNewBuilder25.setDebugMessage("Client does not support user choice billing.");
        builderNewBuilder25.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder26 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder26.setResponseCode(-2);
        builderNewBuilder26.setDebugMessage("Play Store version installed does not support external offer.");
        zzt = builderNewBuilder26.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder27 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder27.setResponseCode(-2);
        builderNewBuilder27.setDebugMessage("Play Store version installed does not support multi-item purchases with season pass in one cart.");
        zzu = builderNewBuilder27.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder28 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder28.setResponseCode(-2);
        builderNewBuilder28.setDebugMessage("Play Store version installed does not support querying AutoPay plan purchase.");
        zzv = builderNewBuilder28.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder29 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder29.setResponseCode(-2);
        builderNewBuilder29.setDebugMessage("Play Store version installed does not support including suspended subscriptions.");
        zzw = builderNewBuilder29.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder30 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder30.setResponseCode(5);
        builderNewBuilder30.setDebugMessage("Unknown feature");
        zzx = builderNewBuilder30.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder31 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder31.setResponseCode(-2);
        builderNewBuilder31.setDebugMessage("Play Store version installed does not support get billing config.");
        zzy = builderNewBuilder31.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder32 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder32.setResponseCode(-2);
        builderNewBuilder32.setDebugMessage("Query product details with serialized docid is not supported.");
        zzz = builderNewBuilder32.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder33 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder33.setResponseCode(-2);
        builderNewBuilder33.setDebugMessage("Play Store version installed does not support launching external offer flow.");
        zzA = builderNewBuilder33.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder34 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder34.setResponseCode(4);
        builderNewBuilder34.setDebugMessage("Item is unavailable for purchase.");
        zzB = builderNewBuilder34.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder35 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder35.setResponseCode(-2);
        builderNewBuilder35.setDebugMessage("Query product details with developer specified account is not supported.");
        zzC = builderNewBuilder35.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder36 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder36.setResponseCode(-2);
        builderNewBuilder36.setDebugMessage("Play Store version installed does not support alternative billing only.");
        zzD = builderNewBuilder36.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder37 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder37.setResponseCode(5);
        builderNewBuilder37.setDebugMessage("To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.");
        zzE = builderNewBuilder37.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder38 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder38.setResponseCode(6);
        builderNewBuilder38.setDebugMessage("An error occurred while retrieving billing override.");
        zzF = builderNewBuilder38.build();
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder39 = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder39.setResponseCode(-2);
        builderNewBuilder39.setDebugMessage("Play Store version installed does not support the provided billing program.");
        builderNewBuilder39.build();
    }

    static com.android.billingclient.api.BillingResult zza(int i, java.lang.String str) {
        com.android.billingclient.api.BillingResult.Builder builderNewBuilder = com.android.billingclient.api.BillingResult.newBuilder();
        builderNewBuilder.setResponseCode(i);
        builderNewBuilder.setDebugMessage(str);
        return builderNewBuilder.build();
    }
}
